apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  "{{ template "k8s-sc.service_company" . }}"
  labels:
{{ include "k8s-sc.labels" . | indent 4 }}
    component: {{ .Values.service_company.name }}
spec:
  replicas: {{ .Values.service_company.relicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
{{ include "k8s-sc.matchLabels" . | indent 6 }}
      component: {{ .Values.service_company.name }}
  template:
    metadata:
      labels:
{{ include "k8s-sc.matchLabels" .| indent 8 }}
        component: {{ .Values.service_company.name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}  
      {{- end -}}  
      containers:
      - image: "{{ .Values.service_company.image.repository }}:{{ .Values.service_company.image.tag }}"
        name: service-company
        {{- if .Values.service_company.resources }} {{/* setting resources config*/}}
        resources:        
{{ toYaml .Values.service_company.resources | indent 10 }}
        {{- end }}
        ports: {{/* setting prots config */}}
        {{- if .Values.common.pod.ports }}
{{ toYaml .Values.common.pod.ports | indent 8 }}
        {{- end }}
        {{- if .Values.service_company.ports }}
{{ toYaml .Values.service_company.ports | indent 8 }}
        {{- end }}
        env: {{/* setting env config */}}
        {{- if .Values.common.pod.env }}
{{ toYaml .Values.common.pod.env | indent 8 }}
        {{- end }}
        {{- if .Values.service_company.env }}
{{ toYaml .Values.service_company.env | indent 8 }}
        {{- end }}
        volumeMounts: {{/* setting volumeMounts config */}}
        {{- if .Values.common.pod.volumeMounts }}
{{ toYaml .Values.common.pod.volumeMounts | indent 8 }}
        {{- end }}
        {{- if .Values.service_company.volumeMounts }}
{{ toYaml .Values.service_company.volumeMounts | indent 8 }}
        {{- end }}
        imagePullPolicy: IfNotPresent
      volumes: {{/* setting volumes config */}}
      {{- if .Values.common.pod.volumes }}
{{ toYaml .Values.common.pod.volumes | indent 6 }}
      {{- end }}
      {{- if .Values.common.pod.volumes }}
{{ toYaml .Values.service_company.volumes | indent 6 }}
      {{- end }}
      nodeSelector:
      {{- with .Values.service_company.nodeSelector }}
{{ toYaml . | indent 6 }}
      {{- end}}
      affinity:
      {{- with .Values.service_company.affinity }}
{{ toYaml . | indent 6 }}
      {{- end}}
      tolerations:
      {{- with .Values.service_company.tolerations }}
{{ toYaml . | indent 6 }}
      {{- end}}

