kind: Service
apiVersion: v1
metadata:
  name: "{{ template "k8s-sc.service_company" . }}"
  namespace: {{ .Values.common.ns }}
  labels:
{{ include "k8s-sc.labels" . | indent 4 }}
    component: {{ .Values.service_company.name }}
spec:
  selector:
{{ include "k8s-sc.matchLabels" . | indent 4 }}
    component: {{ .Values.service_company.name }}
  type: ClusterIP
  ports: {{/* setting ports config */}}
    {{- if .Values.common.services.ports }}
{{ toYaml .Values.common.services.ports | indent 2 }}
    {{- end }}

