apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  "{{ template "k8s-sc.eureka_backup01" . }}"
  labels:
{{ include "k8s-sc.labels" . | indent 4 }}
    component: {{ .Values.eureka_backup01.name }}
spec:
  replicas: {{ .Values.eureka_backup01.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
{{ include "k8s-sc.matchLabels" . | indent 6 }}
      component: {{ .Values.eureka_backup01.name }}
  template:
    metadata:
      labels:
{{ include "k8s-sc.matchLabels" .| indent 8 }}
        component: {{ .Values.eureka_backup01.name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}  
      {{- end -}}  
      containers:
      - image: "{{ .Values.eureka_backup01.image.repository }}:{{ .Values.eureka_backup01.image.tag }}"
        name: {{ .Values.eureka_backup01.name }}
        {{- if .Values.eureka_backup01.resources }} {{/* setting resources config*/}}
        resources:        
{{ toYaml .Values.eureka_backup01.resources | indent 10 }}
        {{- end }}
        ports: {{/* setting prots config */}}
        {{- if .Values.eureka_backup01.ports }}
{{ toYaml .Values.eureka_backup01.ports | indent 8 }}
        {{- end }}
        env: {{/* setting env config */}}
        {{- if .Values.common.pod.env }}
{{ toYaml .Values.common.pod.env | indent 8 }}
        {{- end }}
        {{- if .Values.eureka_backup01.env }}
{{ toYaml .Values.eureka_backup01.env | indent 8 }}
        {{- end }}
        volumeMounts: {{/* setting volumeMounts config */}}
        {{- if .Values.common.pod.volumeMounts }}
{{ toYaml .Values.common.pod.volumeMounts | indent 8 }}
        {{- end }}
        {{- if .Values.eureka_backup01.volumeMounts }}
{{ toYaml .Values.eureka_backup01.volumeMounts | indent 8 }}
        {{- end }}
        imagePullPolicy: IfNotPresent
      volumes: {{/* setting volumes config */}}
      {{- if .Values.common.pod.volumes }}
{{ toYaml .Values.common.pod.volumes | indent 6 }}
      {{- end }}
      {{- if .Values.common.pod.volumes }}
{{ toYaml .Values.eureka_backup01.volumes | indent 6 }}
      {{- end }}
      nodeSelector:
      {{- with .Values.eureka_backup01.nodeSelector }}
{{ toYaml . | indent 6 }}
      {{- end}}
      affinity:
      {{- with .Values.eureka_backup01.affinity }}
{{ toYaml . | indent 6 }}
      {{- end}}
      tolerations:
      {{- with .Values.eureka_backup01.tolerations }}
{{ toYaml . | indent 6 }}
      {{- end}}

